<?php

namespace Tests;

use App\Models\Utilisateur;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
	use CreatesApplication;
	use RefreshDatabase;

	public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = factory(Utilisateur::class)->create();
        $this->session(["user" => $user]);
    }
}
